import React, { useState } from 'react';
import { MailIcon, SpinnerIcon, DocumentIcon } from './Icons';
import { api } from '../services/api';

export const ReportEmailForm: React.FC = () => {
    const [status, setStatus] = useState<'idle' | 'sending' | 'success' | 'error'>('idle');
    const [errorMessage, setErrorMessage] = useState('');
    const [attachedFile, setAttachedFile] = useState<string>('');
    
    const [formData, setFormData] = useState({
        recipient: 'ADA.complaint@usdoj.gov',
        subject: 'Formal Notification: WCAG / ADA Compliance Audit Failure',
        message: 'To Whom It May Concern,\n\nPlease find attached our automated web accessibility audit report generated by Aria. This report highlights multiple violations of the Web Content Accessibility Guidelines (WCAG) 2.1, indicating non-compliance with the Americans with Disabilities Act (ADA).\n\nWe are formally submitting this report for review and request that the necessary enforcement actions be taken to ensure digital equity.\n\nThank you,\n[Your Name/Organization]'
    });

    const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => {
        const { name, value } = e.target;
        if (name === 'attachment') {
            setAttachedFile(value);
        } else {
            setFormData(prev => ({ ...prev, [name]: value }));
        }
    };

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault();
        setStatus('sending');
        setErrorMessage('');

        try {
            // Include a mock organization to satisfy the backend API type requirement
            await api.sendEmail({ ...formData, organization: "Department of Justice" });
            setStatus('success');
            
            // Reset to idle after 5 seconds to allow sending another
            setTimeout(() => {
                setStatus('idle');
                setAttachedFile('');
            }, 5000);
        } catch (error) {
            console.error("Failed to send email:", error);
            setStatus('error');
            setErrorMessage('Failed to send the email. Please verify your connection.');
        }
    };

    return (
        <div className="w-full max-w-[95%] mx-auto bg-white/60 backdrop-blur-md p-8 rounded-2xl shadow-[0_8px_30px_rgb(0,0,0,0.04)] border border-[#9DB68B]/30 flex flex-col h-[85vh]">
            <div className="flex-shrink-0 mb-6 flex items-center space-x-3">
                <div className="w-12 h-12 rounded-xl bg-earth-primary/20 flex items-center justify-center">
                    <MailIcon className="w-6 h-6 text-earth-primary" />
                </div>
                <div>
                    <h2 className="text-2xl font-bold text-earth-dark font-serif">File Official Claim</h2>
                    <p className="text-earth-muted text-sm">Transmit audit reports directly to enforcement agencies.</p>
                </div>
            </div>

            {status === 'success' && (
                <div className="absolute inset-0 z-50 bg-white/80 backdrop-blur-sm rounded-2xl flex flex-col items-center justify-center text-center animate-in fade-in duration-500">
                    <div className="w-24 h-24 bg-green-100 rounded-full flex items-center justify-center mb-6 shadow-xl">
                        <svg className="w-12 h-12 text-green-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={3} d="M5 13l4 4L19 7" />
                        </svg>
                    </div>
                    <h3 className="text-3xl font-bold text-green-800 mb-2 font-serif">Transmission Successful</h3>
                    <p className="text-lg text-green-700 max-w-md">Your claim {attachedFile ? 'and attached audit report have' : 'has'} been securely forwarded to {formData.recipient}.</p>
                </div>
            )}

            {status === 'error' && (
                <div className="mb-6 p-4 bg-red-50 border border-red-200 rounded-xl">
                    <p className="text-red-700 font-medium">{errorMessage}</p>
                </div>
            )}

            <form onSubmit={handleSubmit} className={`flex-1 flex flex-col transition-opacity duration-300 ${status === 'success' ? 'opacity-0 pointer-events-none' : 'opacity-100'}`}>
                
                <div className="flex-1 grid grid-cols-1 lg:grid-cols-12 gap-8 mb-6 min-h-0">
                    
                    {/* Left Column: Recipient, Attachment */}
                    <div className="lg:col-span-4 flex flex-col space-y-8">
                        <div>
                            <label className="block text-sm font-medium text-earth-dark mb-2">Recipient Email</label>
                            <input 
                                type="email" 
                                name="recipient"
                                value={formData.recipient}
                                onChange={handleChange}
                                required
                                className="w-full px-4 py-3 rounded-xl bg-white/80 border border-[#D4C5B0] focus:border-[#9DB68B] focus:ring-2 focus:ring-[#9DB68B]/20 outline-none transition-all text-earth-dark shadow-sm"
                            />
                        </div>
                        
                        <div className="flex flex-col">
                            <label className="block text-sm font-medium text-earth-dark mb-2">Audit Report Attachment (Optional)</label>
                            <div className="relative">
                                <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                                    <DocumentIcon className={`h-5 w-5 ${attachedFile ? 'text-[#9DB68B]' : 'text-earth-muted'}`} />
                                </div>
                                <select 
                                    name="attachment"
                                    value={attachedFile}
                                    onChange={handleChange}
                                    className={`w-full pl-10 pr-10 py-3 rounded-xl bg-white/80 border focus:border-[#9DB68B] focus:ring-2 focus:ring-[#9DB68B]/20 outline-none transition-all text-earth-dark shadow-sm appearance-none cursor-pointer
                                        ${attachedFile ? 'border-[#9DB68B] font-medium' : 'border-[#D4C5B0]'}`}
                                >
                                    <option value="">-- No Attachment --</option>
                                    <option value="Aria_Audit_Report_plantpico_com.pdf">Aria_Audit_Report_plantpico_com.pdf</option>
                                    <option value="Aria_Audit_Report_example_com.pdf">Aria_Audit_Report_example_com.pdf</option>
                                    <option value="Aria_Audit_Report_target_com.pdf">Aria_Audit_Report_target_com.pdf</option>
                                </select>
                                <div className="absolute inset-y-0 right-0 flex items-center px-4 pointer-events-none">
                                    <svg className="w-4 h-4 text-earth-muted" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M19 9l-7 7-7-7"></path>
                                    </svg>
                                </div>
                            </div>
                        </div>

                        {/* Visual indicator if a file is attached */}
                        {attachedFile && (
                            <div className="p-4 bg-[#9DB68B]/10 border border-[#9DB68B]/30 rounded-xl flex items-start space-x-3 mt-4 animate-in fade-in">
                                <DocumentIcon className="w-8 h-8 text-[#9DB68B] flex-shrink-0" />
                                <div>
                                    <p className="text-sm font-bold text-earth-dark">Ready to Transmit</p>
                                    <p className="text-xs text-earth-muted truncate w-full" title={attachedFile}>{attachedFile}</p>
                                </div>
                            </div>
                        )}
                    </div>

                    {/* Right Column: Subject, Message */}
                    <div className="lg:col-span-8 flex flex-col space-y-6">
                        <div>
                            <label className="block text-sm font-medium text-earth-dark mb-2">Subject</label>
                            <input 
                                type="text" 
                                name="subject"
                                value={formData.subject}
                                onChange={handleChange}
                                required
                                className="w-full px-4 py-3 rounded-xl bg-white/80 border border-[#D4C5B0] focus:border-[#9DB68B] focus:ring-2 focus:ring-[#9DB68B]/20 outline-none transition-all text-earth-dark shadow-sm font-medium"
                            />
                        </div>

                        <div className="flex-1 flex flex-col">
                            <label className="block text-sm font-medium text-earth-dark mb-2">Message Body</label>
                            <textarea 
                                name="message"
                                value={formData.message}
                                onChange={handleChange}
                                required
                                className="flex-1 w-full px-5 py-4 rounded-xl bg-white/80 border border-[#D4C5B0] focus:border-[#9DB68B] focus:ring-2 focus:ring-[#9DB68B]/20 outline-none transition-all text-earth-dark resize-none shadow-sm text-sm leading-relaxed"
                            ></textarea>
                        </div>
                    </div>
                </div>

                {/* Submit Footer */}
                <div className="flex-shrink-0 pt-4 border-t border-[#9DB68B]/20 mt-auto">
                    <button 
                        type="submit" 
                        disabled={status === 'sending' || status === 'success'}
                        className={`w-full py-4 rounded-xl font-bold text-white shadow-md transition-all flex items-center justify-center space-x-2 text-lg
                            ${status === 'sending' || status === 'success' 
                                ? 'bg-[#9DB68B]/70 cursor-not-allowed' 
                                : 'bg-[#9DB68B] hover:bg-[#85A371] hover:-translate-y-1 hover:shadow-xl'}`}
                    >
                        {status === 'sending' ? (
                            <>
                                <SpinnerIcon className="w-6 h-6 animate-spin" />
                                <span>Transmitting Claim to DOJ...</span>
                            </>
                        ) : (
                            <>
                                <MailIcon className="w-6 h-6" />
                                <span>Submit Official Claim {attachedFile ? '& Attachment' : ''}</span>
                            </>
                        )}
                    </button>
                </div>
            </form>
        </div>
    );
};
